version: "3"
services:
  postgresql:
    image: postgres:12.2
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bl1nkker
    mem_limit: 36g

  redis:
    image: redis:5.0.7
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=511
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  postgres-data:
  redis-data:
  nc_data:
