from plugins.core.iplugin import IPlugin
from plugins.models import Meta, PluginInput, PluginOutput


class SamplePlugin(IPlugin):
    def __init__(self, logger):
        super().__init__(logger)
        self.meta = Meta(
            name="Sample Plugin",
            description="sample plugin template",
            version="1.1.1",
            # must be generated by https://shortunique.id/ service
            # todo: resolve plugin id consistency problem
            web_id="sfjt6uvQon7xnrXtuuBVxzZYKjIRSexl",
        )

    def invoke(self, input: PluginInput) -> PluginOutput:
        self._plugin_services.transcriber_proxy.get(payload={})
        self.logger.debug(f"Text: {input.text} -> {self.meta}")
        return PluginOutput(text=f"processed: {input.text}")
