from plugins.models import Meta
from plugins.core.iplugin import IPlugin


class SamplePlugin(IPlugin):
    def __init__(self, logger):
        super().__init__(logger)
        self.meta = Meta(
            name="Sample Plugin",
            description="sample plugin template",
            version="1.1.1",
            # must be generated by https://shortunique.id/ service
            web_id="sfjt6uvQon7xnrXtuuBVxzZYKjIRSexl",
        )

    def invoke(self, text: str) -> str:
        print("invoker")
        self.logger.debug(f"Text: {text} -> {self.meta}")
        return text
