plugin_input = {
    "data": {
        "teacher_name": "Dr. John Smith",
        "course_title": "Introduction to 500 bucks",
        "course_code": "CS101",
        "course_type": "Compulsory",
        "course_level": "Bachelor - first cycle",
        "course_academic_year": 2025,
        "course_semester": "Fall",
        "course_credits": 6,
        "course_teachers": [
            {
                "title": "Prof.",
                "fullname": "John Smith",
                "email": "john.smith@example.com",
            },
            {
                "title": "Dr.",
                "fullname": "Alice Johnson",
                "email": "alice.johnson@example.com",
            },
        ],
        "course_outcomes": "By the end of the course, students will be able to understand the fundamentals of AI, apply search algorithms, analyze data using machine learning techniques, and critically evaluate AI applications.",
        "course_prerequisites": "Basic knowledge of programming in Python and introductory linear algebra.",
        "course_content": [
            {"week": 1, "topic": "Introduction to AI", "contract_hours": 2, "sss": 1},
            {
                "week": 2,
                "topic": "History and Applications",
                "contract_hours": 2,
                "sss": 1,
            },
            {"week": 3, "topic": "Search Algorithms I", "contract_hours": 2, "sss": 1},
            {"week": 4, "topic": "Search Algorithms II", "contract_hours": 2, "sss": 1},
            {"week": 5, "topic": "Game Playing", "contract_hours": 2, "sss": 1},
            {
                "week": 6,
                "topic": "Knowledge Representation",
                "contract_hours": 2,
                "sss": 1,
            },
            {"week": 7, "topic": "Reasoning", "contract_hours": 2, "sss": 1},
            {"week": 8, "topic": "Planning", "contract_hours": 2, "sss": 1},
            {"week": 9, "topic": "Uncertainty in AI", "contract_hours": 2, "sss": 1},
            {
                "week": 10,
                "topic": "Machine Learning Basics",
                "contract_hours": 2,
                "sss": 1,
            },
            {"week": 11, "topic": "Supervised Learning", "contract_hours": 2, "sss": 1},
            {
                "week": 12,
                "topic": "Unsupervised Learning",
                "contract_hours": 2,
                "sss": 1,
            },
            {"week": 13, "topic": "Neural Networks", "contract_hours": 2, "sss": 1},
            {"week": 14, "topic": "Ethics in AI", "contract_hours": 2, "sss": 1},
            {
                "week": 15,
                "topic": "Course Review & Project Presentations",
                "contract_hours": 2,
                "sss": 1,
            },
        ],
        "course_content_contact_hours_total": 30,
        "course_content_sss_total": 15,
        "course_required_literature": [
            "Russell, S., & Norvig, P. (2021). Artificial Intelligence: A Modern Approach."
        ],
        "course_recommended_literature": [
            "Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning."
        ],
        "course_internet_sources": [
            "https://ai.google",
            "https://towardsdatascience.com",
        ],
        "course_other_sources": ["Lecture slides provided by instructor"],
        "course_languages": ["English language"],
        "course_assessment_methods_isc_1": [
            {
                "week": 3,
                "title": "Quiz 1",
                "topic": "Search Algorithms",
                "form": "Quiz",
                "points": 10,
                "weight": 20,
            },
            {
                "week": 6,
                "title": "Midterm Exam",
                "topic": "Reasoning & Search",
                "form": "Exam",
                "points": 30,
                "weight": 40,
            },
            {
                "week": 10,
                "title": "Project Proposal",
                "topic": "AI Applications",
                "form": "Presentation",
                "points": 20,
                "weight": 40,
            },
        ],
        "course_assessment_methods_isc_2": [
            {
                "week": 12,
                "title": "Quiz 2",
                "topic": "Machine Learning",
                "form": "Quiz",
                "points": 10,
                "weight": 20,
            },
            {
                "week": 14,
                "title": "Project Report",
                "topic": "Applied AI",
                "form": "Report",
                "points": 30,
                "weight": 40,
            },
            {
                "week": 15,
                "title": "Final Presentation",
                "topic": "AI Project",
                "form": "Presentation",
                "points": 20,
                "weight": 40,
            },
        ],
        "course_assessment_final_exam_topic": "Comprehensive evaluation of AI techniques",
        "course_assessment_final_exam_form": "Written exam",
    },
    "text": None,
}
