# File storage settings
TEST_DATA_PATH: $PROJECT/_test_files
FILE_STORAGE_PATH: $HOME/.omnisect/files
FILE_STORAGE_PATH_TEST: $HOME/.omnisect/test_files
PLUGINS_FOLDER_PATH: $PROJECT/plugins/plugins

# Log settings
LOG_LEVEL: DEBUG
